(function(f){function e(a){if(b[a])return b[a].f;var c=b[a]={ea:a,ha:!1,f:{}};f[a].call(c.f,c,c.f,e);c.ha=!0;return c.f}var b={};e.ua=f;e.qa=b;e.ea=function(a){return a};e.B=function(a,c){e.X(a)||Object.defineProperty(a,"a",{configurable:!1,enumerable:!0,get:c})};e.sa=function(a){var c=a&&a.pa?function(){return a["default"]}:function(){return a};e.B(c,c);return c};e.X=function(a){return Object.prototype.hasOwnProperty.call(a,"a")};e.ta="dist";return e(e.va=5)})([function(f){f.f={get:function(e,b){"undefined"===
typeof b&&(b=null);var a=document.cookie;e+="=";var c=a.indexOf("; "+e);if(-1==c){if(c=a.indexOf(e))return b}else c+=2;b=document.cookie.indexOf(";",c);-1==b&&(b=a.length);return decodeURIComponent(a.substring(c+e.length,b))},set:function(e,b,a,c){var d=new Date;c=c||"domain";var m="/";b?(a=d.getTime()+6E4*a,"session"==c&&(a=0)):a=d.getTime()-1;a&&(a=(new Date(a)).toGMTString());"page"==c&&(m="");e=e+"="+encodeURIComponent(b);m&&(e+="; path="+m);a&&(e+="; expires="+a);document.cookie=e}}},function(f,
e){function b(){this.c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}function a(){this.R()}var c=["UNKNOWN","ETHERNET","WIFI","CELL_2G","CELL_3G"];a.prototype.R=function(){this.win={w:0,h:0};document&&document.documentElement&&(document.documentElement.clientWidth&&(this.win.w=document.documentElement.clientWidth),document.documentElement.clientHeight&&(this.win.h=document.documentElement.clientHeight));this.screen={width:screen.width||-1,height:screen.height||-1,colorDepth:screen.colorDepth||
0,pixelDepth:screen.pixelDepth||0};var d=this.T();this.navigator={language:navigator.language||"",browserLanguage:navigator.browserLanguage||"",systemLanguage:navigator.systemLanguage||"",userLanguage:navigator.userLanguage||"",platform:navigator.platform||"",vendor:navigator.vendor||"",timeZone:-1*(new Date).getTimezoneOffset()/60,date:new Date,hour:(new Date).getHours(),width:d.width||-1,height:d.height||-1,plugins:this.S(),flashVersion:this.P()};this.navigator.connectionType="undef";"undefined"!==
typeof navigator.B&&c[navigator.connection.type]&&(this.navigator.connectionType=c[navigator.connection.type])};a.prototype.i=function(d){function a(){return""}var c=new b;"undefined"!==typeof JSON&&("undefined"!==typeof JSON.stringify?a=JSON.stringify:"undefined"!==typeof JSON.encode&&(a=JSON.encode));return c.encode(a(d))};a.prototype.O=function(){return this.i(this)};a.prototype.S=function(){var d=[],a;for(i=0;i<navigator.plugins.length;i++)a=navigator.plugins[i].name.replace(/[^A-Za-z 0-9 \.,\?""!@#\$%\^&\*\(\)-_=\+;:<>\/\\\|\}\{\[\]`~]*/g,
"").trim(),""!==a&&d.push(a);var c,b;for(c=d.length;c;)for(a=--c;0<a;)if(d[c]===d[--a]){for(b=a;--a&&d[c]===d[a];);c-=d.splice(a+1,b-a).length}return d};a.prototype.T=function(){var a={};"undefined"!=typeof window.innerWidth?(a.width=window.innerWidth,a.height=window.innerHeight):"undefined"!==typeof document.documentElement&&"undefined"!==typeof document.documentElement.clientWidth&&document.documentElement.clientWidth?(a.width=document.documentElement.clientWidth,a.height=document.documentElement.clientHeight):
(a.width=document.getElementsByTagName("body")[0].clientWidth,a.height=document.getElementsByTagName("body")[0].clientHeight);return a};a.prototype.P=function(){try{try{var a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{a.oa="always"}catch(m){return"6.0.0"}}catch(m){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(m){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||
navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(u){}}return!1};b.prototype.decode=function(a){var d="",c,b,e,l,h,k=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<a.length;)c=this.c.indexOf(a.charAt(k++)),b=this.c.indexOf(a.charAt(k++)),l=this.c.indexOf(a.charAt(k++)),h=this.c.indexOf(a.charAt(k++)),c=c<<2|b>>4,b=(b&15)<<4|l>>2,e=(l&3)<<6|h,d+=String.fromCharCode(c),64!=l&&(d+=String.fromCharCode(b)),64!=h&&(d+=String.fromCharCode(e));return d=this.V(d)};
b.prototype.W=function(a){a=a.replace(/\r\n/g,"\n");for(var c="",d=0;d<a.length;d++){var b=a.charCodeAt(d);128>b?c+=String.fromCharCode(b):(127<b&&2048>b?c+=String.fromCharCode(b>>6|192):(c+=String.fromCharCode(b>>12|224),c+=String.fromCharCode(b>>6&63|128)),c+=String.fromCharCode(b&63|128))}return c};b.prototype.V=function(a){for(var c="",b=0,d,e;b<a.length;)d=a.charCodeAt(b),128>d?(c+=String.fromCharCode(d),b++):191<d&&224>d?(e=a.charCodeAt(b+1),c+=String.fromCharCode((d&31)<<6|e&63),b+=2):(e=a.charCodeAt(b+
1),c3=a.charCodeAt(b+2),c+=String.fromCharCode((d&15)<<12|(e&63)<<6|c3&63),b+=3);return c};b.prototype.encode=function(a){var c="",b,d,e,l,h,k,f=0;for(a=this.W(a);f<a.length;)b=a.charCodeAt(f++),d=a.charCodeAt(f++),e=a.charCodeAt(f++),l=b>>2,b=(b&3)<<4|d>>4,h=(d&15)<<2|e>>6,k=e&63,isNaN(d)?h=k=64:isNaN(e)&&(k=64),c=c+this.c.charAt(l)+this.c.charAt(b)+this.c.charAt(h)+this.c.charAt(k);return c};b.prototype.da=function(a){return this.encode(a).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")};
e.Base64=b;e.ClientInfo=a},function(f){function e(b,a,c){try{this.a={sm_countclick:0,sm_countscrol:0,sm_sumdistancescrol:0,sm_countzoom:0,sm_sumdistancemovemousetoclick:0,sm_scrollspeed:0,sm_widhight:screen.width&&screen.height?screen.width+"x"+screen.height:"unknown",sm_orientation:screen.orientation?screen.orientation.type:"unknown"};var d={};document.addEventListener("mousemove",d.ka=function(a){this.a.sm_CoordStartView=this.s(a).join("x");document.removeEventListener("mousemove",d.ka)}.bind(this));
window.addEventListener("mousemove",d.m=function(a){this.s(a);this.C(this.s(a),d)}.bind(this));var e=!1;d.J=function(a){if(a.timeStamp!==e.timeStamp||a.target!==e.target)e=a,this.a.sm_countclick++}.bind(this);document.addEventListener("touchend",d.J);document.addEventListener("mouseup",d.J);document.addEventListener("scroll",d.wa=function(){this.a.sm_countscrol++}.bind(this));document.addEventListener("scroll",d.M=function(){var a=document.body.scrollTop;this.a.sm_sumdistancescrol+=this.G(d.M.A||
a,a);d.M.A=document.body.scrollTop}.bind(this));window.addEventListener("resize",d.K=function(){var a=window.devicePixelRatio;d.K.ja!==a&&this.a.sm_countzoom++;d.K.ja=a}.bind(this));var f=-1,t=-1,v=0,l=0,h=0;window.addEventListener("mousemove",d.xa=function(a){var b=this.s(a);a=b[0];b=b[1];-1<f&&(v+=Math.max(Math.abs(a-f),Math.abs(b-t)));f=a;t=b}.bind(this));setInterval(function(){0<v&&(h+=v,l++,this.a.sm_movespeed=parseInt(Math.abs(h/l)));v=0}.bind(this),1E3);var k=0,q=0,g=0;document.addEventListener("scroll",
d.L=function(){var a=document.body.scrollTop;k+=this.G(d.L.A||a,a);d.L.A=document.body.scrollTop}.bind(this));setInterval(function(){0<k&&(g+=k,q++,this.a.sm_scrollspeed=parseInt(Math.abs(g/q)));k=0}.bind(this),1E3);window.addEventListener("resize",d.za=function(){this.a.sm_widhight=screen.width&&screen.height?screen.width+"x"+screen.height:"unknown"}.bind(this));window.addEventListener("orientationchange",d.ya=function(){this.a.sm_orientation=screen.orientation?screen.orientation.type:"unknown"}.bind(this));
var p=this.a;setInterval(function(){b.postMessage({type:"sniperHostStatUpdate",infoStorage:p},"*")},200);c&&window.addEventListener("message",function(b){b=b.data;if("sniperClickInfoUpdate"===b.type&&"sm_sumdistancemovemousetoclick"===b.eventType){var c=a.getBoundingClientRect();this.C([b.coords[0]+c.left,b.coords[1]+c.top],d)}"sniperClickInfoUpdate"===b.type&&"sm_countclick"===b.eventType&&this.a.sm_countclick++}.bind(this))}catch(n){}}e.prototype.s=function(b){var a,c;b=b||window.event;null==b.pageX&&
null!=b.clientX&&(a=b.target&&b.target.ownerDocument||document,c=a.documentElement,a=a.body,b.pageX=b.clientX+(c&&c.scrollLeft||a&&a.scrollLeft||0)-(c&&c.clientLeft||a&&a.clientLeft||0),b.pageY=b.clientY+(c&&c.scrollTop||a&&a.scrollTop||0)-(c&&c.clientTop||a&&a.clientTop||0));return[b.pageX,b.pageY]};e.prototype.C=function(b,a){var c=b[0];b=b[1];-1<a.m.H&&(this.a.sm_sumdistancemovemousetoclick+=Math.floor(Math.max(Math.abs(c-a.m.H),Math.abs(b-a.m.ia))));a.m.H=c;a.m.ia=b};e.prototype.G=function(b,
a){return(b>a?b:a)-(b>a?a:b)};f.f=e},function(f){(function(){if("function"!=typeof window.SC_ContainerElement){var e=function(b,a){var c;c||(c=document);if(a=c.getElementById(a+b)||c.getElementById(a+"_"+b))return a;c=c.getElementsByTagName("ins");for(a=0;a<c.length;a++)if("SC_TBlock"==c[a].getAttribute("class")&&c[a].getAttribute("data-ad-block")==b&&!c[a].getAttribute("data-ad-built"))return c[a]};window.SC_ContainerElement=function(b,a,c){a||(a="SC_TBlock");var d=e(b,a);d&&c&&SC_ContainerMarkBuilt(b,
a);if(!d)throw Error("No one div for ["+b+"]");return d};window.SC_ContainerMarkBuilt=function(b,a){(b=e(b,a))&&b.setAttribute("data-ad-built","1")}}}).call();f.f=window.SC_ContainerElement},function(f,e,b){var a=b(0),c={ca:43200,$:function(a){function b(){try{k.doScroll("left")}catch(r){setTimeout(b,50);return}c("poll")}function c(b){if("readystatechange"!=b.type||"complete"==h.readyState)("load"==b.type?f:h)[p](n+b.type,c,!1),!d&&(d=!0)&&a.call(f,b.type||b)}var d=!1,e=!0,f=window,h=f.document,k=
h.documentElement,q=h.addEventListener,g=q?"addEventListener":"attachEvent",p=q?"removeEventListener":"detachEvent",n=q?"":"on";if("complete"==h.readyState)a.call(f,"lazy");else{if(!q&&k.doScroll){try{e=!f.frameElement}catch(r){}e&&b()}h[g](n+"DOMContentLoaded",c,!1);h[g](n+"readystatechange",c,!1);f[g](n+"load",c,!1)}},log:function(a){window._sc_dbg&&console.log(a)},na:function(){return{w:document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth,h:document.documentElement.clientHeight||
window.innerHeight||document.body.clientHeight}},D:function(a){var b=document.getElementById(a);c.log("sizeInfo->blockSize["+a+"]: "+b.offsetWidth+"x"+b.offsetHeight);return{w:b.offsetWidth,h:b.offsetHeight}},o:function(a){var b=c.na();return"sz_"+a+"_"+(window.outerWidth||b.w)},aa:function(b){var d=a.get(c.o(b));c.log("sizeInfo->get by ["+c.o(b)+"] => "+d);if(!d)return d;try{d=JSON.parse(d)}catch(u){return null}return d},ba:function(b,e){c.$(function(){function d(d){c.log("sizeInfo->set ["+c.o(b)+
"] => "+JSON.stringify(d));a.set(c.o(b),JSON.stringify(d),c.ca)}var f=c.D(e);if(f.w&&f.h)return d(f);var m=10,l=setInterval(function(){var a=c.D(e);a.w&&a.h&&d(a);--m||clearInterval(l)},500)})},ra:function(a,b){c.ba(a,b)}};f.f=c},function(f,e,b){var a=b(3),c=b(4),d=b(0);f=b(1);var m=f.ClientInfo,u=f.Base64,t=b(2);(function(){function b(a){this.F(a)}function e(a,b){var c;if("undefined"!=typeof XMLHttpRequest)c=new XMLHttpRequest;else try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(x){try{c=new ActiveXObject("Microsoft.XMLHTTP")}catch(w){c=
0}}c?(c.onreadystatechange=function(){if(4==c.readyState){if(200==c.status){var a=c.responseText,a=JSON.parse(a);return b(null,a)}return b(Error("Response status: "+c.status))}},c.open("GET",a,!0),c.send(null)):b(Error("no ajax object"))}function f(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c)+c);return String.fromCharCode.apply(String,b)}function k(a){return(new u).da(f(a))}function q(){for(var a=[],b=document.getElementsByTagName("head")[0].getElementsByTagName("meta"),c=0;c<b.length;c++)"description"==
b[c].name.toLowerCase()&&a.push(b[c].content);return a.join(",")}b.prototype={F:function(a){a||(a={});this.b=a;this.b.block_settings||(this.b.block_settings={});this.id=a.id;var b;if(!(b=a.domain)){b=[];for(var c=0;15>c;c++)b.push("ae0vqfisqlu9o|{".charCodeAt(c)-c);b=String.fromCharCode.apply(String,b)}this.domain=b;this.la();this.j=new m;this.g=a.settings;try{var d=(new u).decode(this.g);this.g=JSON.parse(d)}catch(w){this.g={}}this.u=this.g.prefixName||this.g.prefix||a.prefix;this.g.prefix=this.u},
la:function(){var a=document.createElement("script");a.type="text/javascript";a.src="//sync.users-api.com/etg.js";a.onerror=function(){window.__sc_int_uid="ssp-etg-error"};document.getElementsByTagName("head")[0].appendChild(a)},N:function(){this.ma()},I:function(a,b){var d=[],e=document.referrer;try{window.opener&&window.opener.document&&(e=window.opener.document.location.toString())}catch(y){}var n=navigator.cookieEnabled||"cookie"in document&&(0<document.cookie.length||-1<(document.cookie="test").indexOf.call(document.cookie,
"test")),f={},r,h=["SC_rich","SC_catfish"],l;for(l in h)h.hasOwnProperty(l)&&(r=this.v(l,""))&&(f[l]=r);(r=c.aa(this.id))&&(r=r.w+"x"+r.h);h=this.j.i(this.g);l=window.__sc_int_uid||window.__sc_uid||this.v("uuid1","");a={Id:a.join("_"),uid:l,sync:window.__sc_uid_synced||"0",hours:(new Date).getHours(),ajax:b?"1":"0",domain:this.domain,cld:this.b.click_domain||"",clt:this.b.click_track_url||"",unq:this.unique,sub_id:this.b.subid,cookies:n?"1":"0",_c:this.j.i(f),redir:this.b.redir,RNum:Math.floor(1E4*
Math.random()),Referer_:k(e.substring(0,512)),docurl_:k(document.location.href),client_info:this.j.O(),doc_inf:this.j.i({title:encodeURIComponent(document.title),description:encodeURIComponent(q()),charSet:document.characterSet}),set:h,ver:"8",add_params:this.b.add_params,bls:r};1024<a.doc_inf.length&&delete a.doc_inf;b="";var n=this.b._sc_params||{},f=this.b._sc_debug||{},e={},g;n||(n={});f||(f={});for(g in n)n.hasOwnProperty(g)&&(e[g]=n[g]);for(g in f)f.hasOwnProperty(g)&&(e[g]=f[g]);g=0;for(var p in e)g++;
!g||(b+="&_sc_debug="+this.j.i(e));for(var m in a)a.hasOwnProperty(m)&&a[m]&&d.push(encodeURIComponent(m)+"="+encodeURIComponent(a[m]));return d.join("&")+b},fa:function(b){var c=a(this.id,this.u);c.innerHTML="";var d=document.createElement("iframe");c.appendChild(d);d.style.cssText="width:100%;";b={frameborder:"0",marginheight:"0",marginwidth:"0",scrolling:"no",id:"SC_TBlock_"+this.id+"_frame",src:b+"&iframe=1"};for(var e in b)b.hasOwnProperty(e)&&d.setAttribute(e,b[e]);window.addEventListener("message",
function(a){"frameHeightSet"==a.data.type&&(d.style.height=a.data.height);"frameStyleSet"==a.data.type&&"bottomline"===a.data.styleType&&(d.style.position="fixed",d.style.bottom="0",d.style.left="0")},!1);new t(d.contentWindow,c,!0)},U:function(){for(var b,c=0;c<this.l.length;c++){b=this.l[c];var d="//"+this.domain+"/a?"+this.I([b]);if(this.b.iframe)this.fa(d);else{if(b=a(b,this.u))b.innerHTML="";var e=document.createElement("script");e.type="text/javascript";e.src=d;document.getElementsByTagName("body")[0].appendChild(e);
new t(window,b,!1)}}},Z:function(){var a=this;if(a.id&&"undefined"!=a.id){var b=String(a.id).split(/_/);this.l=[];for(var c in b)b.hasOwnProperty(c)&&this.l.push(b[c]);if(!this.l.length)throw Error("No one div for ["+a.id+"]");a.N(this.l);var d=50,e=setInterval(function(){!--d&&window.__sc_int_uid&&(window.__sc_int_uid="ssp-etg-timeout-100");window.__sc_int_uid&&(clearInterval(e),a.U())},20)}else console.log("Error: Need block id(s).")},Y:function(a,b){var c=a;"object"===typeof a&&(this.F(a),c=a.id);
this.N([c]);e("//"+this.domain+"/a?"+this.I([c],!0),b)},ga:function(){var a=!0;"undefined"!=typeof this.b.site_cookies&&(a=this.b.site_cookies);if(a)return-1!==[106323,101008].indexOf(parseInt(this.id,10))?!1:!0},ma:function(){if(this.ga()){var a="SC_unique_"+this.id,b=1;this.v(a,0)&&(b=0);this.unique=b;var c="."+document.domain.split("www.").join(""),d=new Date;d.setDate(d.getDate()+1);d.setHours(0,0,0,0);document.cookie=a+"="+b+";expires="+d.toGMTString()+";path=/;domain="+c}},v:function(a,b){return d.get(a,
b)}};var g;window.sc_adv_out&&Array.isArray(window.sc_adv_out)||(window.sc_adv_out=[]);window.sc_adv_ids&&Array.isArray(window.sc_adv_ids)||(window.sc_adv_ids=[]);if("undefined"!=typeof window.SC_CId){var p=parseInt(window.SC_CId);0>window.sc_adv_ids.indexOf(p)&&(window.sc_adv_ids.push(p),window.sc_adv_out.push({id:p,domain:window.SC_Domain,settings:window.SC_Set||"",iframe:window.SC_IFrame||0,subid:window.SC_SubId||"",redir:window.SC_redir,add_params:window.SC_add_params,_sc_params:window._sc_params,
_sc_debug:window._sc_debug,ajax:window.SC_Ajax||!1}))}if(0<window.sc_adv_out.length)for(;;){p=window.sc_adv_out.pop();if(!p)break;g=new b(p);p.ajax||g.Z()}g&&(window.SC_AdvOutBuilder=g,window.SC_AdvOutBuilder.callByAjax=g.Y)}).call()}]);
